---
deployment:
  tasks:
     - export DEPLOYPATH=/home/fbsstaging/public_html/omind-new/wp-content/themes/xmoze-child
     - /bin/cp -r /home/fbsstaging/repositories/omind-dev-werdpress/ * $DEPLOYPATH